class Error(Exception):
    pass


class ValueOutOfBound(Error):
    pass
